//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CLMS_DBEntities : DbContext
    {
        public CLMS_DBEntities()
            : base("name=CLMS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_FileUploadDetails> tbl_FileUploadDetails { get; set; }
        public virtual DbSet<tbl_PatientDetails> tbl_PatientDetails { get; set; }
        public virtual DbSet<tbl_VitalSingsDetails> tbl_VitalSingsDetails { get; set; }
        public virtual DbSet<tbl_VitalSingsDetails_History> tbl_VitalSingsDetails_History { get; set; }
    }
}
