//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KidneyFunctionsReports
    {
        public System.Guid KFR_TestReportID { get; set; }
        public System.Guid PatientID { get; set; }
        public System.DateTime TestDate { get; set; }
        public string SCreatinine { get; set; }
        public string UrineACR { get; set; }
        public string Urea { get; set; }
        public string Bun { get; set; }
        public string SUricAcid { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
