//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LiverFunctionReports
    {
        public System.Guid LFR_TestReportID { get; set; }
        public System.Guid PatientID { get; set; }
        public System.DateTime TestDate { get; set; }
        public string SBilirubin { get; set; }
        public string SGOT { get; set; }
        public string SGPT { get; set; }
        public string GGT { get; set; }
        public string SAlkPhosphate { get; set; }
        public string SProtein { get; set; }
        public string Albumin { get; set; }
        public string Globulin { get; set; }
        public string AGRatio { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
