//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FileUploadDetails
    {
        public System.Guid FileUploadID { get; set; }
        public Nullable<System.Guid> PatientID { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public string TestType { get; set; }
        public string TestName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> TestReportID { get; set; }
        public string FileName { get; set; }
        public string FileDispalyName { get; set; }
        public string FilePath { get; set; }
    }
}
