//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLMS_App.ReportsDE {
    
    
    public partial class Report_BoneProfileDE {
        
        /// <summary>
        /// ucBoneProfileDE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CLMS_App.UserControls.ucBoneProfileDE ucBoneProfileDE;
    }
}
